### ISSUE TITLE
[Bug] Got error when clicking on cluster button in Backstage 1.38.0

### ISSUE THREAD

**Issue by tommy04062019** [jfvilas/plugin-kwirth-log#1]
@jfvilas : In Backstage 1.38.0, kwirth-log has something wrong:
Chrome:
```
TypeError
Cannot read properties of undefined (reading 'LOG')
Call Stack
 onSelectCluster
  node_modules/@jfvilas/plugin-kwirth-log/dist/components/EntityKwirthLogContent/EntityKwirthLogContent.esm.js:125:96
 onClick
  node_modules/@jfvilas/plugin-kwirth-log/dist/components/ClusterList/ClusterList.esm.js:34:913
 HTMLUnknownElement.callCallback
  node_modules/react-dom/cjs/react-dom.development.js:4164:14
 Object.invokeGuardedCallbackDev
  node_modules/react-dom/cjs/react-dom.development.js:4213:16
 invokeGuardedCallback
  node_modules/react-dom/cjs/react-dom.development.js:4277:31
 invokeGuardedCallbackAndCatchFirstError
  node_modules/react-dom/cjs/react-dom.development.js:4291:25
 executeDispatch
  node_modules/react-dom/cjs/react-dom.development.js:9041:3
 processDispatchQueueItemsInOrder
  node_modules/react-dom/cjs/react-dom.development.js:9073:7
 processDispatchQueue
  node_modules/react-dom/cjs/react-dom.development.js:9086:5
 dispatchEventsForPlugins
  node_modules/react-dom/cjs/react-dom.development.js:9097:3

```
Firefox:
```
TypeError
_jfvilas_kwirth_common__WEBPACK_IMPORTED_MODULE_1__.InstanceConfigChannelEnum is undefined
Call Stack
 onSelectCluster
  node_modules/@jfvilas/plugin-kwirth-log/dist/components/EntityKwirthLogContent/EntityKwirthLogContent.esm.js:125:9
 onClick
  node_modules/@jfvilas/plugin-kwirth-log/dist/components/ClusterList/ClusterList.esm.js:34:921
 callCallback
  node_modules/react-dom/cjs/react-dom.development.js:4164:14
 invokeGuardedCallbackDev
  node_modules/react-dom/cjs/react-dom.development.js:4213:16
 invokeGuardedCallback
  node_modules/react-dom/cjs/react-dom.development.js:4277:31
 invokeGuardedCallbackAndCatchFirstError
  node_modules/react-dom/cjs/react-dom.development.js:4291:25
 executeDispatch
  node_modules/react-dom/cjs/react-dom.development.js:9041:42
 processDispatchQueueItemsInOrder
  node_modules/react-dom/cjs/react-dom.development.js:9073:22
 processDispatchQueue
  node_modules/react-dom/cjs/react-dom.development.js:9086:37
 dispatchEventsForPlugins
  node_modules/react-dom/cjs/react-dom.development.js:9097:23


```

**Comment by tommy04062019** [comment]
I think it due to this dependency. I tried in my old Backstage where kwirth still works, but when I remove yarn.lock, node-modules and run yarn install again, the error appear as in other Backstage versions
```
"@jfvilas/kwirth-common@npm:^0.3.55":
  version: 0.3.81
  resolution: "@jfvilas/kwirth-common@npm:0.3.81"
  dependencies:
    guid: "npm:^0.0.12"
  checksum: 10c0/0965c0a7b56a7a65f6ea2d2405270a97599fd923e9ac397e9ad8ad6b82c24e97b56548057db115e2e0d3e6f29267dd6b97e8fc17e3a64b8091c9cf21943247ea
  languageName: node
  linkType: hard
```
Package @jfvilas/kwirth-common@^0.3.55 is locked to version 0.3.81
